Feature/density chart
dataiku/dss-plugin-geospatial-toolkit pull request #1
Opened 2020-12-22 11:18 UTC by tdesfont

2021-01-11 13:37 UTC, HenriChabert requested changes
Nice work !
I did not add reviews on the files that we checked together by Zoom. I'll look at it once you changed and tried what we discussed of :)

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +        var val = webAppConfig[param.name];
As said in the call, use `const` or `let` rather that `var`

2021-01-11 13:37 UTC, HenriChabert commented on js/leftBarParamsModule.js
> +    };
I would place the default values into constants (for example: `const DEFAULT_INTENSITY = 50`)

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +def numerical_filter(df, filter):
name.
```suggestion
def numerical_filter(df, filter_):
```
If possible, it is better not to use builtin names in functions. The general workaround is to use var name `filter_`, that is the main role of placing an underscore at the end of a var

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +        if k != '___dku_no_value___':
It would be better to use a constant DKU_NO_VALUE for that string.

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +                conditions += [~df[filter['column']].isnull()]
Is there a reason you are using a dict for `excludedValues` while you are only using it if the value is True ? Couldn't you just use a list with excluded values?

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +    for k, v in filter['excludedValues'].items():
nitpicking: If using the var only in a Python script, prefer snake_case to remain consistent.

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +    if len(conditions) == 0:
nitpick: More pythonic to use `if not conditions`

2021-01-11 13:37 UTC, HenriChabert commented on python-lib/dku_filtering/filtering.py
> +        return df[reduce(lambda c1, c2: c1 & c2, conditions[1:], conditions[0])]
Nice way to do it!

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +        if (val == undefined || val == "") {
```suggestion
        if (val === null || val === "") {
```
null returns true for both undefined and null, which is what you want unless you want null to be considered as ok.
You should also use `===` syntax that will run a deep check (verify type and value). For example, 1 == '1' returns true while 1 === '1' returns false. Using `===` makes you totally control what you want to check.

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +        webAppDesc.topBarParams.forEach(p => {checkMandatoryParameters(p, webAppConfig)});
nitpick: When method has only one instruction, you do not need to use `{...}`.

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +    }
You do not need to use `else`. If condition in if verified, the function will return and the following instructions won't be executed.
```suggestion
    if (max === min) return 0;
    var scale = 1 / (max - min);
    return Math.pow(Math.max(0,(value - min)*scale), 2);
```

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +        console.warn("backend error: ", error);
Why using `console.warn()` insted of `console.error()` ?

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +        return fetch(getUrl(path) + '?' + $.param(args), {
```suggestion
        return fetch(`${getUrl(path)}?${$.param(args)}`, {
```
nitpick: I think that this syntax is most of the time clearer

2021-01-11 13:37 UTC, HenriChabert commented on resource/dku-helpers.js
> +                    response.text().then(text => dataiku.webappMessages.displayFatalError(`Backend error:\n${text}.\nCheck backend log for more information.`))
Indeed for the backend start. Why don' t you put it in app.js?

2021-01-11 13:37 UTC, HenriChabert commented on resource/leftBarParamsTemplate.html
> +&lt;!&ndash;TODO: Potentially leave only this &ndash;&gt;
I have tried before to just copy/paste the code of DSS and it has never worked. I think it is better to understand and to replicate only what you need.
About the dku-slider, it could be a great idea. Have you already tried using it ?
About the rest, it would indeed be good to replicate DKU style but it is already pretty nice I think.

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/webapp.json
> +        "description": "Custom chart to visualize datasets as graphs. These datasets must have source and target columns.",
Did you forget to modify it when you used the code of Stan?

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/webapp.json
> +        "icon": "icon-link"
Would use a different icon.

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/body.html
> +<script type="text/javascript"></script>
Empty script

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/backend.py
> +        if len(filters) > 0:  # apply filters to dataframe
```suggestion
        if filters:  # apply filters to dataframe
```

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/backend.py
> +        lat = [eval(i[6:-1].split(' ')[1]) for i in coordinates]
```suggestion
        long_, lat = zip(*[list(map(float, re.findall("\d+\.\d+", x))) for x in l])
```
Regex is more self explainatory I find but both are good, it is only to present you another way to do. Good practice also to use `long_` as long exists in Python builtin methods

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/app.js
> +    });
I guess this is a test?

2021-01-11 13:37 UTC, HenriChabert commented on webapps/density-custom-chart/app.js
> +        _mapPointer = L.map(_mapId).setView([48.8444529, 2.3718228], 5);
Use constants to set DEFAULT_CENTER and DEFAULT_ZOOM

2021-01-13 14:21 UTC, tdesfont commented on resource/dku-helpers.js
> +        var val = webAppConfig[param.name];
OK replaced mainly by let

2021-01-13 15:09 UTC, tdesfont commented on js/leftBarParamsModule.js
> +    };
Good idea, will do

2021-01-13 15:16 UTC, tdesfont commented on python-lib/dku_filtering/filtering.py
> +def numerical_filter(df, filter):
Agreed

2021-01-13 15:22 UTC, tdesfont commented on resource/dku-helpers.js
> +        if (val == undefined || val == "") {
Noted

2021-01-13 15:28 UTC, tdesfont commented on resource/dku-helpers.js
> +                    response.text().then(text => dataiku.webappMessages.displayFatalError(`Backend error:\n${text}.\nCheck backend log for more information.`))
What should we put in app.js ?

2021-01-13 15:28 UTC, tdesfont commented on webapps/density-custom-chart/webapp.json
> +        "description": "Custom chart to visualize datasets as graphs. These datasets must have source and target columns.",
Yes thanks

2021-01-13 15:33 UTC, tdesfont commented on webapps/density-custom-chart/body.html
> +<script type="text/javascript"></script>
Removed

2021-01-13 15:34 UTC, tdesfont commented on webapps/density-custom-chart/app.js
> +    });
Removed

2021-01-13 15:35 UTC, tdesfont commented on resource/dku-helpers.js
> +        console.warn("backend error: ", error);
Will do

2021-02-08 10:35 UTC, closed without merging